apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: hello-world:latest
        name: astropulse-app
        ports:
        - containerPort: 80
      tolerations:
      - key: "node.cluster.platform.astropulse.io/purchase-option"
        operator: "Equal"
        value: "ondemand"
        effect: "NoSchedule"
      - key: "node.cluster.platform.astropulse.io/type"
        operator: "Equal"
        value: "dataplane"
        effect: "NoSchedule"
