apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: 300Mi
      defaultRequest:
        cpu: "100m"
        memory: 200Mi
      max:
        cpu: "500m"
        memory: 500Mi
      min:
        cpu: "100m"
        memory: 100Mi
