apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    requests.cpu: "1"  # Total CPU requests across all Pods
    requests.memory: 1Gi  # Total memory requests across all Pods
    limits.cpu: "2"  # Total CPU limits across all Pods
    limits.memory: 2Gi  # Total memory limits across all Pods
    pods: "10"  # Total number of Pods
